name = "cf-worker"

workers_dev = true
main = "./workers/app.ts"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2026-06-26"
compatibility_flags = ["nodejs_compat"]
routes = [{ pattern = "kin.codes", custom_domain = true }]

[vars]

[assets]
  directory = "./build/client"
